server:
    error:
        whitelabel:
            enabled: false

    port: 8088


spring:
    application:
        name: Security

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: admin
        url: jdbc:mysql://localhost:3306/english_mcq_bank
        username: root

    mail:
        host: smtp.gmail.com
        password: lafggjxkvhhwuuqj
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: noreplyemail328@gmail.com

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    task:
        execution:
            pool:
                core-size: 5
                max-size: 10

    thymeleaf:
        servlet:
            produce-partial-output-while-processing: false
